In [76]:
import numpy as np
import random
from sklearn.model_selection import train_test_split, KFold, LeaveOneOut

## Creacion del array

In [59]:
# Crear el array de 100 filas con 2 columnas con 0s
q = np.zeros((100,2))

#Se recorrera el arreglo con la finalidad de "rellenarlo"
#Se emplea la funcion random.randint() para asignar un numero entero que este dentro de un rango
#El rango para este caso sera 0-9 y se asignaran
#45, 35 y 25 datos a las 3 clases requeridas
for i in range(0,100):
    if i < 40: #Clase1
        q[i][0] = random.randint(0,9)
        q[i][1] = 1
    elif  i >= 40 and i < 65 :#Clase2
        q[i][0] = random.randint(0,9)
        q[i][1] = 2
    elif i >= 65:#Clase3
        q[i][0] = random.randint(0,9)
        q[i][1] = 3
q 

array([[7., 1.],
       [4., 1.],
       [3., 1.],
       [9., 1.],
       [5., 1.],
       [5., 1.],
       [4., 1.],
       [4., 1.],
       [0., 1.],
       [0., 1.],
       [3., 1.],
       [0., 1.],
       [5., 1.],
       [2., 1.],
       [3., 1.],
       [3., 1.],
       [8., 1.],
       [0., 1.],
       [5., 1.],
       [3., 1.],
       [4., 1.],
       [0., 1.],
       [2., 1.],
       [4., 1.],
       [8., 1.],
       [4., 1.],
       [1., 1.],
       [7., 1.],
       [6., 1.],
       [3., 1.],
       [2., 1.],
       [8., 1.],
       [6., 1.],
       [8., 1.],
       [3., 1.],
       [7., 1.],
       [5., 1.],
       [7., 1.],
       [3., 1.],
       [4., 1.],
       [3., 2.],
       [5., 2.],
       [7., 2.],
       [9., 2.],
       [0., 2.],
       [3., 2.],
       [5., 2.],
       [7., 2.],
       [5., 2.],
       [9., 2.],
       [9., 2.],
       [7., 2.],
       [2., 2.],
       [5., 2.],
       [6., 2.],
       [1., 2.],
       [7., 2.],
       [1., 2.],
       [2., 2.

In [60]:
#Se realiza una permutacion aleatoria de los datos generados
q = np.random.permutation(q)
q

array([[4., 3.],
       [5., 3.],
       [0., 3.],
       [5., 3.],
       [4., 1.],
       [3., 1.],
       [2., 2.],
       [2., 2.],
       [2., 3.],
       [6., 1.],
       [6., 3.],
       [3., 1.],
       [0., 3.],
       [2., 3.],
       [8., 1.],
       [1., 3.],
       [1., 2.],
       [2., 1.],
       [9., 2.],
       [5., 2.],
       [0., 3.],
       [5., 2.],
       [3., 1.],
       [4., 3.],
       [7., 1.],
       [9., 3.],
       [6., 3.],
       [5., 1.],
       [1., 3.],
       [2., 3.],
       [9., 2.],
       [5., 1.],
       [6., 1.],
       [4., 1.],
       [7., 1.],
       [0., 1.],
       [3., 2.],
       [4., 1.],
       [7., 1.],
       [5., 1.],
       [0., 1.],
       [2., 1.],
       [0., 2.],
       [4., 1.],
       [9., 2.],
       [6., 2.],
       [2., 3.],
       [5., 1.],
       [5., 3.],
       [3., 2.],
       [9., 1.],
       [2., 2.],
       [1., 3.],
       [4., 1.],
       [1., 1.],
       [0., 3.],
       [7., 2.],
       [2., 3.],
       [5., 2.

In [61]:
## Verificar si los datos no se han modificado, se debe tener 40-1's, 35-2's y 25-3's
n = 0
b = 0
c = 0 

for i in range (0,100):
    
    if q[i][1] == 1:
        n = n+1
    
    elif q[i][1] == 2:
        b = b+1
    elif q[i][1] == 3:
        c = c+1
print(n)
print(b)
print(c)

40
25
35


## Hold-Out

In [62]:
# Se realiza la division del set por el metodo HOLD OUT
train,test = train_test_split(q,train_size =0.6, test_size=0.4)
# Verificamos que cada uno de los conjuntos contenga el porcentaje requerido
print(len(train),len(test))

(60, 40)


In [63]:
print('Los datos de entrenamiento son:\n')
print(train)
print("Los datos de validacion son:\n ")
print(test)
 

Los datos de entrenamiento son:

[[5. 3.]
 [6. 3.]
 [4. 3.]
 [0. 3.]
 [2. 2.]
 [5. 2.]
 [1. 3.]
 [4. 3.]
 [8. 1.]
 [3. 1.]
 [2. 1.]
 [0. 1.]
 [2. 2.]
 [3. 3.]
 [9. 2.]
 [4. 1.]
 [2. 2.]
 [2. 2.]
 [8. 1.]
 [1. 2.]
 [9. 1.]
 [6. 3.]
 [0. 1.]
 [2. 3.]
 [5. 3.]
 [3. 2.]
 [3. 3.]
 [0. 3.]
 [2. 3.]
 [2. 3.]
 [6. 2.]
 [1. 3.]
 [5. 1.]
 [2. 2.]
 [2. 3.]
 [4. 1.]
 [3. 1.]
 [6. 1.]
 [7. 2.]
 [7. 1.]
 [4. 1.]
 [0. 1.]
 [7. 3.]
 [2. 1.]
 [0. 1.]
 [7. 1.]
 [4. 1.]
 [3. 2.]
 [0. 3.]
 [3. 1.]
 [9. 2.]
 [7. 2.]
 [5. 3.]
 [4. 3.]
 [6. 1.]
 [4. 2.]
 [3. 1.]
 [5. 3.]
 [2. 1.]
 [7. 1.]]
Los datos de validacion son:
 
[[5. 2.]
 [3. 1.]
 [1. 1.]
 [0. 3.]
 [6. 3.]
 [1. 3.]
 [7. 3.]
 [3. 1.]
 [5. 1.]
 [7. 2.]
 [2. 3.]
 [3. 1.]
 [2. 3.]
 [1. 3.]
 [3. 1.]
 [4. 3.]
 [1. 2.]
 [5. 2.]
 [4. 3.]
 [4. 1.]
 [7. 2.]
 [4. 1.]
 [7. 1.]
 [9. 2.]
 [6. 3.]
 [5. 1.]
 [4. 1.]
 [5. 2.]
 [5. 1.]
 [4. 3.]
 [8. 1.]
 [0. 2.]
 [9. 3.]
 [6. 2.]
 [0. 3.]
 [3. 2.]
 [0. 1.]
 [5. 1.]
 [8. 1.]
 [6. 3.]]


## K-Fold

In [64]:
#Implementacion del metodo K-Fold
#se inicializa el numero de folds en 10
kf = KFold(n_splits= 10)
kf.get_n_splits(q)
print(kf)

KFold(n_splits=10, random_state=None, shuffle=False)


In [73]:
z = 0
for train_index, test_index in kf.split(q):

    X_train, X_test = q[train_index], q[test_index]
    print("\nFold: %d"%(z))
    print("TRAIN:\n")
    for i in range (0,len(train_index)):
        print(X_train[i])
    print("TEST:\n")
    for i in range (0,len(test_index)):
        print(X_test[i])
    z = z+1


Fold: 0
TRAIN:

[6. 3.]
[3. 1.]
[0. 3.]
[2. 3.]
[8. 1.]
[1. 3.]
[1. 2.]
[2. 1.]
[9. 2.]
[5. 2.]
[0. 3.]
[5. 2.]
[3. 1.]
[4. 3.]
[7. 1.]
[9. 3.]
[6. 3.]
[5. 1.]
[1. 3.]
[2. 3.]
[9. 2.]
[5. 1.]
[6. 1.]
[4. 1.]
[7. 1.]
[0. 1.]
[3. 2.]
[4. 1.]
[7. 1.]
[5. 1.]
[0. 1.]
[2. 1.]
[0. 2.]
[4. 1.]
[9. 2.]
[6. 2.]
[2. 3.]
[5. 1.]
[5. 3.]
[3. 2.]
[9. 1.]
[2. 2.]
[1. 3.]
[4. 1.]
[1. 1.]
[0. 3.]
[7. 2.]
[2. 3.]
[5. 2.]
[3. 3.]
[8. 1.]
[0. 3.]
[7. 2.]
[4. 3.]
[7. 2.]
[2. 1.]
[6. 3.]
[8. 1.]
[5. 2.]
[0. 1.]
[4. 1.]
[4. 2.]
[2. 2.]
[1. 2.]
[4. 1.]
[6. 2.]
[3. 2.]
[6. 3.]
[7. 2.]
[6. 3.]
[5. 1.]
[0. 1.]
[8. 1.]
[3. 1.]
[4. 3.]
[4. 3.]
[2. 2.]
[1. 3.]
[3. 1.]
[3. 1.]
[5. 3.]
[7. 1.]
[2. 3.]
[4. 3.]
[3. 1.]
[3. 1.]
[0. 1.]
[3. 3.]
[7. 3.]
[7. 3.]
TEST:

[4. 3.]
[5. 3.]
[0. 3.]
[5. 3.]
[4. 1.]
[3. 1.]
[2. 2.]
[2. 2.]
[2. 3.]
[6. 1.]

Fold: 1
TRAIN:

[4. 3.]
[5. 3.]
[0. 3.]
[5. 3.]
[4. 1.]
[3. 1.]
[2. 2.]
[2. 2.]
[2. 3.]
[6. 1.]
[0. 3.]
[5. 2.]
[3. 1.]
[4. 3.]
[7. 1.]
[9. 3.]
[6. 3.]
[5. 1.]
[1. 3.]
[2. 3.]

## Leave-One-Out

In [47]:
# Implementacion del metodo Leave-One-Out
loo = LeaveOneOut()
loo.split(q)

<generator object split at 0x7ff296ca6d20>

In [74]:
#Inicia
z = 0
for train_ix, test_ix in loo.split(q):
	# split data
    #print("TRAIN:", train_ix, "TEST:", test_ix)
    print("Set:%d"%(z))
    X_train, X_test = q[train_ix, :], q[test_ix, :]
    print("Train:\n")
    for i in range (len(X_train)):
        print(X_train[i])
    print("Test:")
    print(X_test)
    z = z+1

Set:0
Train:

[5. 3.]
[0. 3.]
[5. 3.]
[4. 1.]
[3. 1.]
[2. 2.]
[2. 2.]
[2. 3.]
[6. 1.]
[6. 3.]
[3. 1.]
[0. 3.]
[2. 3.]
[8. 1.]
[1. 3.]
[1. 2.]
[2. 1.]
[9. 2.]
[5. 2.]
[0. 3.]
[5. 2.]
[3. 1.]
[4. 3.]
[7. 1.]
[9. 3.]
[6. 3.]
[5. 1.]
[1. 3.]
[2. 3.]
[9. 2.]
[5. 1.]
[6. 1.]
[4. 1.]
[7. 1.]
[0. 1.]
[3. 2.]
[4. 1.]
[7. 1.]
[5. 1.]
[0. 1.]
[2. 1.]
[0. 2.]
[4. 1.]
[9. 2.]
[6. 2.]
[2. 3.]
[5. 1.]
[5. 3.]
[3. 2.]
[9. 1.]
[2. 2.]
[1. 3.]
[4. 1.]
[1. 1.]
[0. 3.]
[7. 2.]
[2. 3.]
[5. 2.]
[3. 3.]
[8. 1.]
[0. 3.]
[7. 2.]
[4. 3.]
[7. 2.]
[2. 1.]
[6. 3.]
[8. 1.]
[5. 2.]
[0. 1.]
[4. 1.]
[4. 2.]
[2. 2.]
[1. 2.]
[4. 1.]
[6. 2.]
[3. 2.]
[6. 3.]
[7. 2.]
[6. 3.]
[5. 1.]
[0. 1.]
[8. 1.]
[3. 1.]
[4. 3.]
[4. 3.]
[2. 2.]
[1. 3.]
[3. 1.]
[3. 1.]
[5. 3.]
[7. 1.]
[2. 3.]
[4. 3.]
[3. 1.]
[3. 1.]
[0. 1.]
[3. 3.]
[7. 3.]
[7. 3.]
Test:
[[4. 3.]]
Set:1
Train:

[4. 3.]
[0. 3.]
[5. 3.]
[4. 1.]
[3. 1.]
[2. 2.]
[2. 2.]
[2. 3.]
[6. 1.]
[6. 3.]
[3. 1.]
[0. 3.]
[2. 3.]
[8. 1.]
[1. 3.]
[1. 2.]
[2. 1.]
[9. 2.]
[5. 2.]
[0. 3.]
[5. 

[3. 1.]
[0. 3.]
[2. 3.]
[8. 1.]
[1. 3.]
[2. 1.]
[9. 2.]
[5. 2.]
[0. 3.]
[5. 2.]
[3. 1.]
[4. 3.]
[7. 1.]
[9. 3.]
[6. 3.]
[5. 1.]
[1. 3.]
[2. 3.]
[9. 2.]
[5. 1.]
[6. 1.]
[4. 1.]
[7. 1.]
[0. 1.]
[3. 2.]
[4. 1.]
[7. 1.]
[5. 1.]
[0. 1.]
[2. 1.]
[0. 2.]
[4. 1.]
[9. 2.]
[6. 2.]
[2. 3.]
[5. 1.]
[5. 3.]
[3. 2.]
[9. 1.]
[2. 2.]
[1. 3.]
[4. 1.]
[1. 1.]
[0. 3.]
[7. 2.]
[2. 3.]
[5. 2.]
[3. 3.]
[8. 1.]
[0. 3.]
[7. 2.]
[4. 3.]
[7. 2.]
[2. 1.]
[6. 3.]
[8. 1.]
[5. 2.]
[0. 1.]
[4. 1.]
[4. 2.]
[2. 2.]
[1. 2.]
[4. 1.]
[6. 2.]
[3. 2.]
[6. 3.]
[7. 2.]
[6. 3.]
[5. 1.]
[0. 1.]
[8. 1.]
[3. 1.]
[4. 3.]
[4. 3.]
[2. 2.]
[1. 3.]
[3. 1.]
[3. 1.]
[5. 3.]
[7. 1.]
[2. 3.]
[4. 3.]
[3. 1.]
[3. 1.]
[0. 1.]
[3. 3.]
[7. 3.]
[7. 3.]
Test:
[[1. 2.]]
Set:17
Train:

[4. 3.]
[5. 3.]
[0. 3.]
[5. 3.]
[4. 1.]
[3. 1.]
[2. 2.]
[2. 2.]
[2. 3.]
[6. 1.]
[6. 3.]
[3. 1.]
[0. 3.]
[2. 3.]
[8. 1.]
[1. 3.]
[1. 2.]
[9. 2.]
[5. 2.]
[0. 3.]
[5. 2.]
[3. 1.]
[4. 3.]
[7. 1.]
[9. 3.]
[6. 3.]
[5. 1.]
[1. 3.]
[2. 3.]
[9. 2.]
[5. 1.]
[6. 1.]
[4. 1.]
[

[4. 3.]
[3. 1.]
[3. 1.]
[0. 1.]
[3. 3.]
[7. 3.]
[7. 3.]
Test:
[[5. 1.]]
Set:32
Train:

[4. 3.]
[5. 3.]
[0. 3.]
[5. 3.]
[4. 1.]
[3. 1.]
[2. 2.]
[2. 2.]
[2. 3.]
[6. 1.]
[6. 3.]
[3. 1.]
[0. 3.]
[2. 3.]
[8. 1.]
[1. 3.]
[1. 2.]
[2. 1.]
[9. 2.]
[5. 2.]
[0. 3.]
[5. 2.]
[3. 1.]
[4. 3.]
[7. 1.]
[9. 3.]
[6. 3.]
[5. 1.]
[1. 3.]
[2. 3.]
[9. 2.]
[5. 1.]
[4. 1.]
[7. 1.]
[0. 1.]
[3. 2.]
[4. 1.]
[7. 1.]
[5. 1.]
[0. 1.]
[2. 1.]
[0. 2.]
[4. 1.]
[9. 2.]
[6. 2.]
[2. 3.]
[5. 1.]
[5. 3.]
[3. 2.]
[9. 1.]
[2. 2.]
[1. 3.]
[4. 1.]
[1. 1.]
[0. 3.]
[7. 2.]
[2. 3.]
[5. 2.]
[3. 3.]
[8. 1.]
[0. 3.]
[7. 2.]
[4. 3.]
[7. 2.]
[2. 1.]
[6. 3.]
[8. 1.]
[5. 2.]
[0. 1.]
[4. 1.]
[4. 2.]
[2. 2.]
[1. 2.]
[4. 1.]
[6. 2.]
[3. 2.]
[6. 3.]
[7. 2.]
[6. 3.]
[5. 1.]
[0. 1.]
[8. 1.]
[3. 1.]
[4. 3.]
[4. 3.]
[2. 2.]
[1. 3.]
[3. 1.]
[3. 1.]
[5. 3.]
[7. 1.]
[2. 3.]
[4. 3.]
[3. 1.]
[3. 1.]
[0. 1.]
[3. 3.]
[7. 3.]
[7. 3.]
Test:
[[6. 1.]]
Set:33
Train:

[4. 3.]
[5. 3.]
[0. 3.]
[5. 3.]
[4. 1.]
[3. 1.]
[2. 2.]
[2. 2.]
[2. 3.]
[6. 1.]
[6. 3.]
[3

[2. 2.]
[1. 3.]
[4. 1.]
[1. 1.]
[0. 3.]
[7. 2.]
[2. 3.]
[5. 2.]
[3. 3.]
[8. 1.]
[0. 3.]
[7. 2.]
[4. 3.]
[7. 2.]
[2. 1.]
[6. 3.]
[8. 1.]
[5. 2.]
[0. 1.]
[4. 1.]
[4. 2.]
[2. 2.]
[1. 2.]
[4. 1.]
[6. 2.]
[3. 2.]
[6. 3.]
[7. 2.]
[6. 3.]
[5. 1.]
[0. 1.]
[8. 1.]
[3. 1.]
[4. 3.]
[4. 3.]
[2. 2.]
[1. 3.]
[3. 1.]
[3. 1.]
[5. 3.]
[7. 1.]
[2. 3.]
[4. 3.]
[3. 1.]
[3. 1.]
[0. 1.]
[3. 3.]
[7. 3.]
[7. 3.]
Test:
[[9. 2.]]
Set:45
Train:

[4. 3.]
[5. 3.]
[0. 3.]
[5. 3.]
[4. 1.]
[3. 1.]
[2. 2.]
[2. 2.]
[2. 3.]
[6. 1.]
[6. 3.]
[3. 1.]
[0. 3.]
[2. 3.]
[8. 1.]
[1. 3.]
[1. 2.]
[2. 1.]
[9. 2.]
[5. 2.]
[0. 3.]
[5. 2.]
[3. 1.]
[4. 3.]
[7. 1.]
[9. 3.]
[6. 3.]
[5. 1.]
[1. 3.]
[2. 3.]
[9. 2.]
[5. 1.]
[6. 1.]
[4. 1.]
[7. 1.]
[0. 1.]
[3. 2.]
[4. 1.]
[7. 1.]
[5. 1.]
[0. 1.]
[2. 1.]
[0. 2.]
[4. 1.]
[9. 2.]
[2. 3.]
[5. 1.]
[5. 3.]
[3. 2.]
[9. 1.]
[2. 2.]
[1. 3.]
[4. 1.]
[1. 1.]
[0. 3.]
[7. 2.]
[2. 3.]
[5. 2.]
[3. 3.]
[8. 1.]
[0. 3.]
[7. 2.]
[4. 3.]
[7. 2.]
[2. 1.]
[6. 3.]
[8. 1.]
[5. 2.]
[0. 1.]
[4. 1.]
[4. 2.]
[2. 2.]
[

[4. 1.]
[7. 1.]
[0. 1.]
[3. 2.]
[4. 1.]
[7. 1.]
[5. 1.]
[0. 1.]
[2. 1.]
[0. 2.]
[4. 1.]
[9. 2.]
[6. 2.]
[2. 3.]
[5. 1.]
[5. 3.]
[3. 2.]
[9. 1.]
[2. 2.]
[1. 3.]
[4. 1.]
[1. 1.]
[0. 3.]
[7. 2.]
[2. 3.]
[5. 2.]
[3. 3.]
[0. 3.]
[7. 2.]
[4. 3.]
[7. 2.]
[2. 1.]
[6. 3.]
[8. 1.]
[5. 2.]
[0. 1.]
[4. 1.]
[4. 2.]
[2. 2.]
[1. 2.]
[4. 1.]
[6. 2.]
[3. 2.]
[6. 3.]
[7. 2.]
[6. 3.]
[5. 1.]
[0. 1.]
[8. 1.]
[3. 1.]
[4. 3.]
[4. 3.]
[2. 2.]
[1. 3.]
[3. 1.]
[3. 1.]
[5. 3.]
[7. 1.]
[2. 3.]
[4. 3.]
[3. 1.]
[3. 1.]
[0. 1.]
[3. 3.]
[7. 3.]
[7. 3.]
Test:
[[8. 1.]]
Set:61
Train:

[4. 3.]
[5. 3.]
[0. 3.]
[5. 3.]
[4. 1.]
[3. 1.]
[2. 2.]
[2. 2.]
[2. 3.]
[6. 1.]
[6. 3.]
[3. 1.]
[0. 3.]
[2. 3.]
[8. 1.]
[1. 3.]
[1. 2.]
[2. 1.]
[9. 2.]
[5. 2.]
[0. 3.]
[5. 2.]
[3. 1.]
[4. 3.]
[7. 1.]
[9. 3.]
[6. 3.]
[5. 1.]
[1. 3.]
[2. 3.]
[9. 2.]
[5. 1.]
[6. 1.]
[4. 1.]
[7. 1.]
[0. 1.]
[3. 2.]
[4. 1.]
[7. 1.]
[5. 1.]
[0. 1.]
[2. 1.]
[0. 2.]
[4. 1.]
[9. 2.]
[6. 2.]
[2. 3.]
[5. 1.]
[5. 3.]
[3. 2.]
[9. 1.]
[2. 2.]
[1. 3.]
[4. 1.]
[1. 1.]
[

[4. 1.]
[7. 1.]
[0. 1.]
[3. 2.]
[4. 1.]
[7. 1.]
[5. 1.]
[0. 1.]
[2. 1.]
[0. 2.]
[4. 1.]
[9. 2.]
[6. 2.]
[2. 3.]
[5. 1.]
[5. 3.]
[3. 2.]
[9. 1.]
[2. 2.]
[1. 3.]
[4. 1.]
[1. 1.]
[0. 3.]
[7. 2.]
[2. 3.]
[5. 2.]
[3. 3.]
[8. 1.]
[0. 3.]
[7. 2.]
[4. 3.]
[7. 2.]
[2. 1.]
[6. 3.]
[8. 1.]
[5. 2.]
[0. 1.]
[4. 1.]
[4. 2.]
[2. 2.]
[1. 2.]
[6. 2.]
[3. 2.]
[6. 3.]
[7. 2.]
[6. 3.]
[5. 1.]
[0. 1.]
[8. 1.]
[3. 1.]
[4. 3.]
[4. 3.]
[2. 2.]
[1. 3.]
[3. 1.]
[3. 1.]
[5. 3.]
[7. 1.]
[2. 3.]
[4. 3.]
[3. 1.]
[3. 1.]
[0. 1.]
[3. 3.]
[7. 3.]
[7. 3.]
Test:
[[4. 1.]]
Set:75
Train:

[4. 3.]
[5. 3.]
[0. 3.]
[5. 3.]
[4. 1.]
[3. 1.]
[2. 2.]
[2. 2.]
[2. 3.]
[6. 1.]
[6. 3.]
[3. 1.]
[0. 3.]
[2. 3.]
[8. 1.]
[1. 3.]
[1. 2.]
[2. 1.]
[9. 2.]
[5. 2.]
[0. 3.]
[5. 2.]
[3. 1.]
[4. 3.]
[7. 1.]
[9. 3.]
[6. 3.]
[5. 1.]
[1. 3.]
[2. 3.]
[9. 2.]
[5. 1.]
[6. 1.]
[4. 1.]
[7. 1.]
[0. 1.]
[3. 2.]
[4. 1.]
[7. 1.]
[5. 1.]
[0. 1.]
[2. 1.]
[0. 2.]
[4. 1.]
[9. 2.]
[6. 2.]
[2. 3.]
[5. 1.]
[5. 3.]
[3. 2.]
[9. 1.]
[2. 2.]
[1. 3.]
[4. 1.]
[1. 1.]
[

[6. 3.]
[8. 1.]
[5. 2.]
[0. 1.]
[4. 1.]
[4. 2.]
[2. 2.]
[1. 2.]
[4. 1.]
[6. 2.]
[3. 2.]
[6. 3.]
[7. 2.]
[6. 3.]
[5. 1.]
[0. 1.]
[8. 1.]
[3. 1.]
[4. 3.]
[4. 3.]
[2. 2.]
[1. 3.]
[3. 1.]
[5. 3.]
[7. 1.]
[2. 3.]
[4. 3.]
[3. 1.]
[3. 1.]
[0. 1.]
[3. 3.]
[7. 3.]
[7. 3.]
Test:
[[3. 1.]]
Set:90
Train:

[4. 3.]
[5. 3.]
[0. 3.]
[5. 3.]
[4. 1.]
[3. 1.]
[2. 2.]
[2. 2.]
[2. 3.]
[6. 1.]
[6. 3.]
[3. 1.]
[0. 3.]
[2. 3.]
[8. 1.]
[1. 3.]
[1. 2.]
[2. 1.]
[9. 2.]
[5. 2.]
[0. 3.]
[5. 2.]
[3. 1.]
[4. 3.]
[7. 1.]
[9. 3.]
[6. 3.]
[5. 1.]
[1. 3.]
[2. 3.]
[9. 2.]
[5. 1.]
[6. 1.]
[4. 1.]
[7. 1.]
[0. 1.]
[3. 2.]
[4. 1.]
[7. 1.]
[5. 1.]
[0. 1.]
[2. 1.]
[0. 2.]
[4. 1.]
[9. 2.]
[6. 2.]
[2. 3.]
[5. 1.]
[5. 3.]
[3. 2.]
[9. 1.]
[2. 2.]
[1. 3.]
[4. 1.]
[1. 1.]
[0. 3.]
[7. 2.]
[2. 3.]
[5. 2.]
[3. 3.]
[8. 1.]
[0. 3.]
[7. 2.]
[4. 3.]
[7. 2.]
[2. 1.]
[6. 3.]
[8. 1.]
[5. 2.]
[0. 1.]
[4. 1.]
[4. 2.]
[2. 2.]
[1. 2.]
[4. 1.]
[6. 2.]
[3. 2.]
[6. 3.]
[7. 2.]
[6. 3.]
[5. 1.]
[0. 1.]
[8. 1.]
[3. 1.]
[4. 3.]
[4. 3.]
[2. 2.]
[1. 3.]
[

In [150]:
for i in range (len(X_train)):
    print(X_train[i])

[6. 2.]
[5. 1.]
[4. 3.]
[7. 3.]
[6. 3.]
[7. 1.]
[6. 2.]
[8. 2.]
[2. 1.]
[3. 2.]
[9. 2.]
[5. 1.]
[5. 2.]
[8. 2.]
[8. 2.]
[5. 2.]
[2. 1.]
[0. 3.]
[2. 2.]
[1. 2.]
[6. 2.]
[2. 1.]
[9. 1.]
[3. 3.]
[8. 1.]
[9. 1.]
[8. 2.]
[9. 2.]
[3. 2.]
[7. 1.]
[2. 3.]
[4. 3.]
[7. 1.]
[0. 1.]
[6. 2.]
[1. 1.]
[6. 1.]
[0. 2.]
[0. 2.]
[1. 2.]
[6. 1.]
[5. 3.]
[0. 2.]
[6. 3.]
[4. 2.]
[3. 2.]
[5. 1.]
[8. 2.]
[6. 1.]
[3. 2.]
[1. 2.]
[8. 1.]
[9. 3.]
[1. 1.]
[3. 1.]
[9. 2.]
[3. 1.]
[6. 3.]
[6. 3.]
[0. 3.]
[4. 1.]
[4. 1.]
[2. 1.]
[5. 1.]
[1. 3.]
[4. 3.]
[4. 2.]
[5. 3.]
[7. 1.]
[4. 1.]
[1. 3.]
[4. 1.]
[7. 3.]
[7. 1.]
[9. 3.]
[9. 2.]
[6. 2.]
[2. 2.]
[4. 3.]
[3. 3.]
[5. 1.]
[8. 1.]
[1. 2.]
[3. 3.]
[2. 1.]
[1. 3.]
[8. 2.]
[1. 1.]
[4. 1.]
[5. 1.]
[6. 1.]
[9. 1.]
[0. 1.]
[4. 2.]
[4. 1.]
[9. 2.]
[7. 2.]
[3. 1.]
[3. 3.]
