## Implementacion de la regla delta

En este notebook se implementa un perceptron, para obtener la salida que tiene una compuerta logica AND:

| A | B | Salida |
| --- | --- | --- |
| 0 | 0 | 0 |
| --- | --- | --- |
| 0 | 1 | 0 |
| --- | --- | --- |
| 1 | 0 | 0 |
| --- | --- | --- |
| 1 | 1 | 1 |


In [1]:
# importamos las librerias necesarias
import numpy as np
import torch
import random

In [2]:
#declaramos las entradas de la compuerta
entradas = np.array([[0.0,0.0],[0.0,1.0],[1.0,0.0],[1.0,1.0]])
entradas

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]])

In [3]:
#declaramos las salidas de la compuerta
salidas = np.array([[0.0],[0.0],[0.0],[1.0]])
salidas

array([[0.],
       [0.],
       [0.],
       [1.]])

In [29]:
# Se inicializan los pesos
#####################################
#Si lo requieres aleatorios :
# pesos = np.zeros(2)
#for i in range(len(pesos)):
#    pesos[i] = random.random()

#####################################

#Si requieres ingresar los pesos que sean de tu agrado
## Verificar que sean tipo float, es decir que lleve el punto decimal
pesos= np.array([1.0,1.0]) 

pesos

array([1., 1.])

In [2]:
## Declaramos alpha y el sesgo a emplear en este caso de estudio 
# Alpha es el learning rate o tasa de aprendizaje que tendra el perceptron
alpha = np.array([0.1])
print(alpha)
# Sesgo o bias 
sesgo = np.array([0.5])
sesgo

[0.1]


array([0.5])

In [24]:
for i in range(0,4):
    print(entradas[i])
    print(salidas[i])

[0. 0.]
[0.]
[0. 1.]
[0.]
[1. 0.]
[0.]
[1. 1.]
[1.]


In [35]:
## Conversion de arrays numpy a tensores con torch.from_numpy()
entrada_T = torch.from_numpy(entradas)
print(entrada_T)
salidas_T = torch.from_numpy(salidas)
print(salidas_T)
pesos_T = torch.from_numpy(pesos)
print(pesos_T)
sesgo_T = torch.from_numpy(sesgo)
print(sesgo_T)
alpha_T = torch.from_numpy(alpha)
print(alpha_T)

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]], dtype=torch.float64)
tensor([[0.],
        [0.],
        [0.],
        [1.]], dtype=torch.float64)
tensor([0.8000, 0.8000], dtype=torch.float64)
tensor([0.5000], dtype=torch.float64)
tensor([0.1000], dtype=torch.float64)


In [17]:
# la funcion step() evalua y a la salida se tiene un escalon para todo valor mayor o igual a cero
def Step (y):
    x = 0
    if (y>=0):
        x = 1
    else:
        x = 0
    return x

# el perceptron realiza las operaciones de un perceptro simple; es decir, multiplica 
# pesos por la entrada, suma esos resultados y -resta el sesgo
# el resultado de esa suma se evalua en la funcion Step()
def Perceptron (x,w,b):
    
    H = torch.add(torch.dot(w,x),-b)
    Y = Step(H)
    return Y

# Calculo del error: salida esperada - prediccion perceptron
def Error (s,y):
    er = torch.add(s,-y)
    return er

## Actualizacion de pesos mediante regla delta
def Actualiza (p,er,en,al, s):
    for i in range(len(p)):
        a = al*en[i]
        p[i] = torch.add(p[i],torch.dot(a,er))
    b = al*-1
    s = torch.add(s,torch.dot(er,b))
    return p,s

In [36]:
##Entrenamiento 
for i in range(0,5): # 5 Epocas
    for j in range(len(entrada_T)): # Se evalua cada patron de entrada 
        salida = Perceptron(entrada_T[j],pesos_T, sesgo_T)
        e  = Error(salidas_T[j], salida)
        print("El error en la epoca", i,"con los patrones",j,"es:",e)
        print("Salida perceptron: ", salida)
        if (e == 0):
            print ("El error es 0")
        else: # si hay error despues de la evaluacion, se calculan nuevos pesos antes de 
            # pasar al siguiente conjunto de patrones en el banco de datos
            print("Modificando pesos: ", pesos_T,"sesgo:", sesgo_T)
            pesos_T, sesgo_T = Actualiza(pesos_T,e,entrada_T[j],alpha_T,sesgo_T)
            print("Actualizacion pesos:", pesos_T,"sesgo:", sesgo_T)

El error en la epoca 0 con los patrones 0 es: tensor([0.], dtype=torch.float64)
Salida perceptron:  0
El error es 0
El error en la epoca 0 con los patrones 1 es: tensor([-1.], dtype=torch.float64)
Salida perceptron:  1
Modificando pesos:  tensor([0.8000, 0.8000], dtype=torch.float64) sesgo: tensor([0.5000], dtype=torch.float64)
Actualizacion pesos: tensor([0.8000, 0.7000], dtype=torch.float64) sesgo: tensor([0.6000], dtype=torch.float64)
El error en la epoca 0 con los patrones 2 es: tensor([-1.], dtype=torch.float64)
Salida perceptron:  1
Modificando pesos:  tensor([0.8000, 0.7000], dtype=torch.float64) sesgo: tensor([0.6000], dtype=torch.float64)
Actualizacion pesos: tensor([0.7000, 0.7000], dtype=torch.float64) sesgo: tensor([0.7000], dtype=torch.float64)
El error en la epoca 0 con los patrones 3 es: tensor([0.], dtype=torch.float64)
Salida perceptron:  1
El error es 0
El error en la epoca 1 con los patrones 0 es: tensor([0.], dtype=torch.float64)
Salida perceptron:  0
El error es 0


In [34]:
len(entrada_T)

4