In [1]:
import numpy as np
import torch
import random

In [2]:
entradas = np.array([[0.0,0.0],[0.0,1.0],[1.0,0.0],[1.0,1.0]])
entradas

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]])

In [3]:
salidas = np.array([[0.0],[0.0],[0.0],[1.0]])
salidas

array([[0.],
       [0.],
       [0.],
       [1.]])

In [29]:
pesos= np.array([1.0,1.0])
#for i in range(len(pesos)):
#    pesos[i] = random.random()
    
pesos

array([1., 1.])

In [30]:
alpha = np.array([0.1])
print(alpha)
sesgo = np.array([0.5])
sesgo

[0.1]


array([0.5])

In [24]:
for i in range(0,4):
    print(entradas[i])
    print(salidas[i])

[0. 0.]
[0.]
[0. 1.]
[0.]
[1. 0.]
[0.]
[1. 1.]
[1.]


In [35]:
entrada_T = torch.from_numpy(entradas)
print(entrada_T)
salidas_T = torch.from_numpy(salidas)
print(salidas_T)
pesos_T = torch.from_numpy(pesos)
print(pesos_T)
sesgo_T = torch.from_numpy(sesgo)
print(sesgo_T)
alpha_T = torch.from_numpy(alpha)
print(alpha_T)

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]], dtype=torch.float64)
tensor([[0.],
        [0.],
        [0.],
        [1.]], dtype=torch.float64)
tensor([0.8000, 0.8000], dtype=torch.float64)
tensor([0.5000], dtype=torch.float64)
tensor([0.1000], dtype=torch.float64)


In [17]:
def Step (y):
    x = 0
    if (y>=0):
        x = 1
    else:
        x = 0
    return x
    
def Perceptron (x,w,b):
    
    H = torch.add(torch.dot(w,x),-b)
    Y = Step(H)
    return Y

def Error (s,y):
    er = torch.add(s,-y)
    return er

def Actualiza (p,er,en,al, s):
    for i in range(len(p)):
        a = al*en[i]
        p[i] = torch.add(p[i],torch.dot(a,er))
    b = al*-1
    s = torch.add(s,torch.dot(er,b))
    return p,s

In [36]:
for i in range(0,5):
    for j in range(len(entrada_T)):
        salida = Perceptron(entrada_T[j],pesos_T, sesgo_T)
        e  = Error(salidas_T[j], salida)
        print("El error en la epoca", i,"con los patrones",j,"es:",e)
        print("Salida perceptron: ", salida)
        if (e == 0):
            print ("El error es 0")
        else:
            print("Modificando pesos: ", pesos_T,"sesgo:", sesgo_T)
            pesos_T, sesgo_T = Actualiza(pesos_T,e,entrada_T[j],alpha_T,sesgo_T)
            print("Actualizacion pesos:", pesos_T,"sesgo:", sesgo_T)

El error en la epoca 0 con los patrones 0 es: tensor([0.], dtype=torch.float64)
Salida perceptron:  0
El error es 0
El error en la epoca 0 con los patrones 1 es: tensor([-1.], dtype=torch.float64)
Salida perceptron:  1
Modificando pesos:  tensor([0.8000, 0.8000], dtype=torch.float64) sesgo: tensor([0.5000], dtype=torch.float64)
Actualizacion pesos: tensor([0.8000, 0.7000], dtype=torch.float64) sesgo: tensor([0.6000], dtype=torch.float64)
El error en la epoca 0 con los patrones 2 es: tensor([-1.], dtype=torch.float64)
Salida perceptron:  1
Modificando pesos:  tensor([0.8000, 0.7000], dtype=torch.float64) sesgo: tensor([0.6000], dtype=torch.float64)
Actualizacion pesos: tensor([0.7000, 0.7000], dtype=torch.float64) sesgo: tensor([0.7000], dtype=torch.float64)
El error en la epoca 0 con los patrones 3 es: tensor([0.], dtype=torch.float64)
Salida perceptron:  1
El error es 0
El error en la epoca 1 con los patrones 0 es: tensor([0.], dtype=torch.float64)
Salida perceptron:  0
El error es 0


In [34]:
len(entrada_T)

4